---
# tasks file for preinstall
- name: Update apt package cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install mariadb Server
  apt:
    name: mariadb-server
    state: present
